apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonic-prod-role-binding
  namespace: sonic-prod
subjects:
- kind: User
  name: sonic-prod-read
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sonic-prod-role
  apiGroup: rbac.authorization.k8s.io