cdi:
  enabled: true

driver:
  enabled: false

toolkit:
  enabled: false
  env:
    - name: CONTAINERD_CONFIG
      value: /etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"

mps:
  enabled: true

mig:
  strategy: none

nfd:
  master:
    hostNetwork: true
  worker:
    hostNetwork: true
